/**
 * solverInterfaces.js
 * 
 * External Solver Interface Module (v2.0.0)
 * 
 * This module provides export interfaces for external solvers.
 * NO SOLVER IMPLEMENTATION - export only.
 * 
 * Interfaces:
 * - MCNP geometry + source export
 * - Thermal boundary conditions export
 * - SRIM stopping power lookup interface
 * 
 * These interfaces allow the digital twin to export data for use with
 * external validated solvers, but do not implement the solvers themselves.
 */

const SolverInterfaces = {
    // ============================================================================
    // MCNP GEOMETRY + SOURCE EXPORT
    // ============================================================================

    /**
     * Export geometry and source definition for MCNP
     * 
     * @param {Object} geometry - Geometry parameters
     *   {targetRadius: number, targetThickness: number, sourceDistance: number, ...}
     * @param {Object} source - Source parameters
     *   {type: 'neutron'|'photon', energy: number, strength: number, ...}
     * @returns {string} MCNP input deck (text format)
     * 
     * Note: This is an export interface only. MCNP solver is not implemented.
     */
    exportMCNPInput: function(geometry, source) {
        let mcnpInput = 'C ============================================================================\n';
        mcnpInput += 'C MCNP Input Deck - Generated by Radioisotope Production Digital Twin v2.0.0\n';
        mcnpInput += 'C ============================================================================\n\n';

        // Cell cards
        mcnpInput += 'C --- CELL CARDS ---\n';
        mcnpInput += `1 1 -${geometry.targetDensity || 1.0} -1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 $ Target\n`;
        mcnpInput += '2 0 1 $ Void\n';
        mcnpInput += '3 0 -2 $ Outside\n\n';

        // Surface cards
        mcnpInput += 'C --- SURFACE CARDS ---\n';
        mcnpInput += `1 PZ ${geometry.targetThickness || 0.1}\n`; // Target front
        mcnpInput += `2 PZ ${-(geometry.targetThickness || 0.1)}\n`; // Target back
        mcnpInput += `3 CZ ${geometry.targetRadius || 1.0}\n`; // Target radius
        mcnpInput += '\n';

        // Data cards
        mcnpInput += 'C --- DATA CARDS ---\n';
        mcnpInput += 'M1 1001 2.0 8016 1.0 $ Target material composition\n';
        mcnpInput += `SDEF POS=0 0 ${geometry.sourceDistance || 10.0} ERG=${source.energy || 14.1} PAR=${source.type === 'neutron' ? 'N' : 'P'}\n`;
        mcnpInput += `SP1 0 1 $ Source spectrum\n`;
        mcnpInput += `F4:N ${source.strength || 1e13} $ Flux tally\n`;
        mcnpInput += 'NPS 1000000 $ Number of particles\n';
        mcnpInput += 'PRINT\n';

        mcnpInput += '\nC ============================================================================\n';
        mcnpInput += 'C END OF MCNP INPUT DECK\n';
        mcnpInput += 'C NOTE: This is an export interface only. MCNP solver is not implemented.\n';
        mcnpInput += 'C ============================================================================\n';

        return mcnpInput;
    },

    // ============================================================================
    // THERMAL BOUNDARY CONDITIONS EXPORT
    // ============================================================================

    /**
     * Export thermal boundary conditions for CFD solver
     * 
     * @param {Object} thermalParams - Thermal parameters
     *   {beamPower: number, coolantFlow: number, heatCapacity: number, ...}
     * @param {Object} geometry - Geometry parameters
     * @returns {Object} Boundary conditions object
     * 
     * Note: This is an export interface only. CFD solver is not implemented.
     */
    exportThermalBoundaryConditions: function(thermalParams, geometry) {
        return {
            metadata: {
                version: '2.0.0',
                export_date: new Date().toISOString(),
                note: 'This is an export interface only. CFD solver is not implemented.'
            },
            boundary_conditions: {
                inlet: {
                    type: 'mass_flow_inlet',
                    mass_flow_rate: thermalParams.coolantFlow || 0.5, // kg/s
                    temperature: thermalParams.inletTemperature || 293.15, // K
                    pressure: thermalParams.inletPressure || 101325 // Pa
                },
                outlet: {
                    type: 'pressure_outlet',
                    pressure: thermalParams.outletPressure || 101325 // Pa
                },
                target_surface: {
                    type: 'heat_flux',
                    heat_flux: (thermalParams.beamPower || 0) / (Math.PI * Math.pow(geometry.targetRadius || 1.0, 2)), // W/m^2
                    area: Math.PI * Math.pow(geometry.targetRadius || 1.0, 2) * 1e-4 // m^2
                }
            },
            material_properties: {
                density: geometry.targetDensity || 1.0, // g/cm^3
                thermal_conductivity: thermalParams.thermalConductivity || 50, // W/(m·K)
                specific_heat: thermalParams.heatCapacity || 4180, // J/(kg·K)
                viscosity: thermalParams.viscosity || 1e-3 // Pa·s
            },
            solver_settings: {
                solver_type: 'CFD',
                turbulence_model: 'k-epsilon',
                discretization: 'finite_volume',
                convergence_criteria: 1e-6
            }
        };
    },

    // ============================================================================
    // SRIM STOPPING POWER LOOKUP INTERFACE
    // ============================================================================

    /**
     * Interface for SRIM stopping power lookup
     * 
     * @param {Object} particleParams - Particle parameters
     *   {type: 'proton'|'alpha'|'ion', energy: number, Z: number, A: number}
     * @param {Object} targetParams - Target parameters
     *   {Z: number, A: number, density: number}
     * @returns {Object} Stopping power data structure
     * 
     * Note: This is an interface only. SRIM lookup is not implemented.
     *       Users must query SRIM database externally.
     */
    srimStoppingPowerInterface: function(particleParams, targetParams) {
        return {
            metadata: {
                version: '2.0.0',
                interface_type: 'SRIM_lookup',
                note: 'This is an interface only. SRIM lookup is not implemented. Users must query SRIM database externally.'
            },
            particle: {
                type: particleParams.type || 'proton',
                Z: particleParams.Z || 1,
                A: particleParams.A || 1,
                energy_MeV: particleParams.energy || 10
            },
            target: {
                Z: targetParams.Z || 29, // Default: Cu
                A: targetParams.A || 63.5,
                density_g_cm3: targetParams.density || 8.96
            },
            lookup_parameters: {
                // These parameters should be used to query SRIM database
                particle_Z: particleParams.Z || 1,
                particle_A: particleParams.A || 1,
                target_Z: targetParams.Z || 29,
                target_A: targetParams.A || 63.5,
                energy_MeV: particleParams.energy || 10
            },
            expected_outputs: {
                stopping_power_electronic: 'dE/dx_e (MeV/(mg/cm^2))',
                stopping_power_nuclear: 'dE/dx_n (MeV/(mg/cm^2))',
                range: 'R (μm)',
                straggling: 'ΔR (μm)'
            }
        };
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SolverInterfaces };
}


